service: flight-guesser
plugins:
  - serverless-python-requirements
custom:
  appName: flight-guesser
  serviceName: flight-guesser-backend
  pythonRequirements:
    slim: true
    useDownloadCache: false
    useStaticCache: false
    layer:
      name: requirements-layer
      description: "Python requirements lambda layer"
      compatibleRuntimes:
        - python3.7
provider:
  name: aws
  region: eu-west-1
  runtime: python3.7
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - '*'
functions:
  get_airports:
    handler: src/service/api.get_airports
    package:
      individually: true
      include:
        - src/service/*
      exclude:
        - ./**
    memorySize: 128
    events:
      - httpApi:
          path: /
          method: get
    timeout: 10
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
  handle_turn:
    handler: src/service/api.handle_turn
    package:
      individually: true
      include:
        - src/service/*
      exclude:
        - ./**
    memorySize: 128
    events:
      - httpApi:
          path: /
          method: post
    timeout: 30
    layers:
      - { Ref: PythonRequirementsLambdaLayer }