version: 0.2

env:
  parameter-store:
    DEPLOY_BUCKET_NAME: "flight-guesser-${STAGE}-host-bucket"
    CF_DISTRIBUTION_ID: "flight-guesser-${STAGE}-cdn-id"

phases:
  install:
    commands:
      - make -j4 install-pipeline-deps

  pre_build:
    commands:
      - |
        VERSION=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json)
        sed -i 's/VERSION_NUMBER/'$VERSION'/g' ./frontend/package.json

  build:
    commands:
      - make deploy-terraform STAGE=$STAGE
      - make deploy-backend STAGE=$STAGE
      - make deploy-frontend STAGE=$STAGE DEPLOY_BUCKET_NAME=$DEPLOY_BUCKET_NAME CF_DISTRIBUTION_ID=$CF_DISTRIBUTION_ID

  post_build:
    finally:
      - |
        if [ $STAGE == "prd" ]; then
            if [ "$1" -ne 0 ]; then
                badge_status=failing
                badge_colour=red
            else
                badge_status=passing
                badge_colour=green
            fi
            curl -s "https://img.shields.io/badge/build-$badge_status-$badge_colour.svg" > "build-status.svg"
            aws s3 cp "build-status.svg" "s3://flight-guesser/build-status.svg" --cache-control no-cache
        fi
