export const AIRPORTS_ENDPOINT =
  "https://BUCKET_ENDPOINT_PLACEHOLDER/airports.json";

export const SINGLEPLAYER_ENDPOINT = "SINGLEPLAYER_ENDPOINT_PLACEHOLDER";

export const MULTIPLAYER_ENDPOINT = "MULTIPLAYER_ENDPOINT_PLACEHOLDER";
