export const AIRPORTS_ENDPOINT = "AIRPORTS_ENDPOINT_PLACEHOLDER";

export const SINGLEPLAYER_ENDPOINT = "SINGLEPLAYER_ENDPOINT_PLACEHOLDER";

export const MULTIPLAYER_ENDPOINT = "MULTIPLAYER_ENDPOINT_PLACEHOLDER";
